# Generated by Django 4.1.1 on 2022-10-18 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iluminacion',
            fields=[
                ('idiluminacion', models.IntegerField(db_column='idIluminacion', primary_key=True, serialize=False)),
                ('color', models.CharField(db_column='Color', max_length=45)),
                ('origen', models.CharField(db_column='Origen', max_length=45)),
                ('regulacion', models.IntegerField(db_column='Regulacion')),
                ('ubicacion', models.CharField(db_column='Ubicacion', max_length=100)),
            ],
            options={
                'db_table': 'iluminacion',
            },
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('idmesas', models.IntegerField(db_column='idMesas', primary_key=True, serialize=False)),
                ('color', models.CharField(db_column='Color', max_length=45)),
                ('tamaño', models.CharField(db_column='Tamaño', max_length=45)),
            ],
            options={
                'db_table': 'mesas',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('idmotivo', models.IntegerField(db_column='idMotivo', primary_key=True, serialize=False)),
                ('indicacion', models.CharField(db_column='Indicacion', max_length=100)),
            ],
            options={
                'db_table': 'motivo',
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('idocupacion', models.IntegerField(db_column='idOcupacion', primary_key=True, serialize=False)),
                ('afiliacion', models.CharField(db_column='Afiliacion', max_length=45)),
            ],
            options={
                'db_table': 'ocupacion',
            },
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('idtablero', models.IntegerField(db_column='idTablero', primary_key=True, serialize=False)),
                ('tamaño', models.CharField(db_column='Tamaño', max_length=45)),
                ('tipo', models.CharField(db_column='Tipo', max_length=45)),
            ],
            options={
                'db_table': 'tablero',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuarios', models.IntegerField(db_column='idUsuarios', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellido', models.CharField(db_column='Apellido', max_length=45)),
                ('celular', models.CharField(db_column='Celular', max_length=45)),
                ('correo', models.CharField(db_column='Correo', max_length=100)),
                ('fecha_nacimiento', models.DateField(db_column='Fecha_nacimiento')),
                ('ocupacion_idocupacion', models.ForeignKey(db_column='Ocupacion_idOcupacion', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.ocupacion')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Salones',
            fields=[
                ('idsalones', models.IntegerField(db_column='idSalones', primary_key=True, serialize=False)),
                ('tamaño', models.CharField(db_column='Tamaño', max_length=45)),
                ('piso', models.IntegerField(db_column='Piso')),
                ('capacidad_estudiantes', models.IntegerField(db_column='Capacidad_estudiantes')),
                ('numero_salon', models.IntegerField()),
                ('iluminacion_idiluminacion', models.ForeignKey(db_column='Iluminacion_idIluminacion', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.iluminacion')),
                ('mesas_idmesas', models.ForeignKey(db_column='Mesas_idMesas', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.mesas')),
                ('tablero_idtablero', models.ForeignKey(db_column='tablero_idtablero', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.tablero')),
            ],
            options={
                'db_table': 'salones',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idreserva', models.IntegerField(db_column='idReserva', primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField(db_column='Hora_inicio')),
                ('hora_fin', models.TimeField(db_column='Hora_fin')),
                ('motivo_idmotivo', models.ForeignKey(db_column='Motivo_idMotivo', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.motivo')),
                ('salones_idsalones', models.ForeignKey(db_column='Salones_idSalones', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.salones')),
                ('usuarios_idusuarios', models.ForeignKey(db_column='Usuarios_idUsuarios', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.usuarios')),
            ],
            options={
                'db_table': 'reserva',
                'unique_together': {('idreserva', 'salones_idsalones', 'usuarios_idusuarios')},
            },
        ),
    ]
